### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by greentea6** [witch-team/witchtools#15]
Thank you Johannes for the youtube link, it was very helpful. And, apologies in advance for basic questions. 

Is it possible to do a country specific analysis?
is it possible to have carbon tax assigned to a specific sector, for example, coal? - also is it possible to do it in only one country [example USA]and keep the rest the same. I am assuming this will need code changes in the core policy file. any guidance on them would be helpful.

**Comment by JohannesEmm** [comment]
Hello,

runnning one country at a time is conceptually possible running it with --only_solve=c_usa for instance.
The carbon tax is applied across sectors by default. Only to specific FUELS would require some tricks that is not so easy to implement, in case please write me a PM.

**Comment by greentea6** [comment]
Thank you! 
Much appreciated!

**Comment by greentea6** [comment]
Hi, 

I am attempting to do a carbon tax sensitivity analysis - to see GDP impacts of higher or lower, or earlier to later carbon tax. However, when I change the parameters in the core policy module, the model gives me function error (please see at the end). Is there any other way to do it? I attempted by changing two parameters below: 


* Carbon tax default options
$ifthen.cx '%policy%'=='ctax'
** Starting year of the carbon tax
$setglobal ctax_year 2022
** Initial level of tax [USD2005/tCO2eq]
$setglobal ctax_initial 80
** Growh rate of tax, in percentage/yr (e.g. 5) or equal to
** 'ramsey' for world average Ramsey consumption discount rate


error message: 

**** GDX ERROR AT LINE 6152 - Unknown GDX symbol Q_EMI_ABAT

**** EXECERROR AT LINE 6152 CLEARED (EXECERROR=0)
**** Exec Error at line 6990: rPower: FUNC DOMAIN: x**y, x=0,y<0

----  42452 Please check execution errors!
**** Exec Error at line 42452: Execution halted: abort$1 'Please check execution errors!'

**** REPORT FILE SUMMARY

opt C:\Users\Paraj\OneDrive\Desktop\witch\conopt.opt
errdat C:\Users\Paraj\OneDrive\Desktop\witch\errors_ssp2_ctax.txt

EXECUTION TIME       =        3.297 SECONDS    111 MB  38.1.0 a1a3b545 WEX-WEI
