### ISSUE TITLE
Correct definition of EU

### ISSUE THREAD

**Issue by JohannesEmm** [witch-team/witchtools#20]
To be decided, but probably the set EU shoujdl contain only the current valid members of the European Union.
that is, 27 countries at present.
It seems in the moment other regions are in there like UK or so, since othereurope in witch20 is flagged as being also EU.
Also, should be based on population majority to wether it belongs to eht EU set or not imho.

**Comment by lolow** [comment]
There are different region sets for europe, as you can see here: https://witchtools.witchmodel.org/reference/index.html#other-functions

There are also available as gams sets in the generated file 'regions.inc'
- eu
- eu27
- eu28
(See https://github.com/witch-team/witchtools/blob/a2f739cc89f6302eb1b3b46e3549475f3a659dd3/R/witch_write_gams.R#L63)

The allocation is based on GDP majority. https://witchtools.witchmodel.org/reference/eu_regions.html

Can you check if `othereurope` is not part of `eu27`? Thanks.

**Comment by JohannesEmm** [comment]
Eu27 and eu28 are fine.
Just EU I think should be only current ei members. Hence no UK.
In witch 20 for some reason also other Europe is part of EU which is wrong.

**Comment by lolow** [comment]
OK, I get it now. The definition of the set/function is ambiguous, either European countries or EU countries. I suggest to wrap `eu` to `eu27` and create a set `is_europe` for European countries. Also check in the witch code which definition was considered when the set `eu` is currently used and change the set if needed.
