### ISSUE TITLE
Debug mode & separation from witch-data

### ISSUE THREAD

**Issue by JohannesEmm** [witch-team/witchtools#3]
A few things from my experience in working with the witchtools package:

- I think it would be really important to have a way in which new users can easily edit their files locally of the whole witch-* framework without having always to use github, ie using witch-data and witchtools in the local folder
- Given it is an independent package would be good to make it work also based on a completely new witch-mode/input and witch-data folder. However, as of now it doesn't work: If I create all the files (ie run translate_witch_data), and then switch to witch-data method on an empty folder, and just rerun the script it gives a few errors: (Yet in my opinion, this should work without errors).
-1) ssp data not found (OK I assume because of the weights).
-2) "database connection not found" not sure which one (globiom? primap for emission weights?).

I think the weights we should or embed them in the package or make them by default use piggyback so it will work with a completely new data folder for other models etc. 

Anyhow we should discuss in a witch strategic meeting!

**Comment by lolow** [comment]
Thanks for the feedbacks:
* About not using witchtools without github. This is very easy with rstudio, in fact this is how I work and develop. I can teach how to do it and you will see how much this is great and easy! (then you can develop new R packages ;) )
*  the witch-data in local is working for me but probably needs more testing (let's add some automatic test for this)
* Independent package, sure. This is in my agenda. Next step was exactly to put weights in the packages. We might create a tasklist so everybody knows where it goes and can also contribute.

**Comment by lolow** [comment]
New version v0.2.0 should solved many of these issue. #7
