### ISSUE TITLE
weights for 'gdp' is defined twice

### ISSUE THREAD

**Issue by lolow** [witch-team/witchtools#6]
Should we use the SSP source or the IMF source?

**Comment by JohannesEmm** [comment]
I would say WDI should be used as is what we use for our gdp calibration.
Also I cleaned up the weights in the branch https://github.com/witch-team/witchtools/tree/witch17eums

**Comment by lolow** [comment]
ok, it would be interesting to see the impact on the WITCH runs with this
change in weights.
I do a big refactoring in the branch convert_gdx, so the package could be
outside witch.

**Comment by JohannesEmm** [comment]
ok great!
ONe more thing/feature request: I think would be good to have a fall back where if piggyback doesn't have the file looks at witch-data and in case finds it uses this data including printing a warning, could be good for new data asily ading it without first uploading on the release while using the standard data from github
