### ISSUE TITLE
allow changing region mappings

### ISSUE THREAD

**Issue by JohannesEmm** [witch-team/witchtools#8]
Right now the region mappings seem hard coded and loaded in the packaged in an rda file.
We should think about a way to allow user specific mappings.
Both for other users, and also for us since now the .inc files used in witch and these hard coded sets are pretty incompatible, or we add a function to add or convert user defined mappings?

**Comment by lolow** [comment]
This is already implemented and explained in the documentation. 
https://witchtools.witchmodel.org/reference/index.html

I can add a specific vignette if you want an example, but you might provide me a specific case to be more helpful. 

You can define your own region mappings, time mappings and weights. Default datasets are used as a default parameter. They can be overloaded with new items. Example:

```
library(witchtools)
newregs <- region_mappings # get default 
newregs <- c(newregs,list(z54 = rm1, h12 = rm2)) # add 2 new mappings
```
where rm1 and rm2 are data.table containing the mapping as a 2-column data.table .

You can use to convert a gdx:
``` 
convert_gdx('input/build/data_climate.gdx','witch17','t30','data_witch17', region_mappings = newregs)
```
or to translate all witch data:
witch_translate_data(region = "r5", timescale = 't30', region_mappings = newregs)

**Comment by JohannesEmm** [comment]
Hi,
ok works very well, great!
Just one comment: the function load_region_mapping was removed correct?
Maybe we can add it again to the package to be able to quickly convert the inc files from the witch repo to the required data table format, what you think?

**Comment by lolow** [comment]
ok, good suggestion. I may change the name but this function might be
useful indeed.

**Comment by lolow** [comment]
@jackjackk @JohannesEmm I added the function in current master
see: https://witchtools.witchmodel.org/reference/witch_region_mapping.html
